name: Read
description: Looks up books information given an issue with an amazon URL.

inputs:
  readFileName:
    description: The directory where you want to save your outputted markdown files.
    default: content/reading


runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.who-to-greet }}

branding:
  icon: "award"
  color: "green"

