name: amazon-lookup
description: Looks up books information given an issue with an amazon URL.

inputs:
  url:
    description: the amazon URL you want to look up
    required: true
  content:
    description: what you want to say about this book
    required: false

outputs:
  book_title:
    description: 'The name of the book'
  book_date:
    description: 'The date you read the book'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.url }}
  - ${{ inputs.content}}

branding:
  icon: "award"
  color: "green"

