name: amazon-lookup
description: Looks up books information given an issue with an amazon URL.

inputs:
  read_directory:
    description: The directory where you want to save your outputted markdown files.
    default: content/reading

outputs:
  book_title:
    description: 'The name of the book'
  book_date:
    description: 'The date you read the book'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.who-to-greet }}

branding:
  icon: "award"
  color: "green"

