name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - run: pip install httmock requests beautifulsoup4 lxml python-slugify
      - run: python -m unittest
